name: trailbase
description: Thing client library for TrailBase.
homepage: https://trailbase.io
repository: https://github.com/trailbaseio/trailbase
version: 0.1.2

environment:
  sdk: ^3.5.3

dependencies:
  crypto: ^3.0.5
  dio: ^5.7.0
  jwt_decoder: ^2.0.1
  logging: ^1.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
