[workspace]
resolver = "2"
members = [
  "examples/custom-binary",
  "trailbase-cli",
  "trailbase-core",
  "trailbase-extension",
  "trailbase-sqlite",
  "vendor/refinery-libsql",
  "vendor/sqlean",
]
default-members = [
  "trailbase-cli",
  "trailbase-core",
  "trailbase-extension",
  "trailbase-sqlite",
]
exclude = [
  "vendor/refinery",
  "vendor/sqlite-loadable",
]

# https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.release]
panic = "unwind"
opt-level = 3
# PGO doesn't work with LTO: https://github.com/llvm/llvm-project/issues/57501
# lto = "off"
lto = true
codegen-units = 1

[workspace.dependencies]
libsql = { package = "libsql", version = "^0.6.0", default-features = false, features = ["core", "serde"] }
refinery = { package = "refinery", path = "vendor/refinery/refinery", default-features = false }
refinery-core = { package = "refinery-core", path = "vendor/refinery/refinery_core" }
refinery-libsql = { package = "refinery-libsql", path = "vendor/refinery-libsql" }
rusqlite = { package = "libsql-rusqlite", version = "^0.32", default-features = false, features = [
    "libsql-experimental",
    "column_decltype",
    "load_extension",
    "modern_sqlite",
    "functions",
    "limits",
    "backup",
] }
sqlite-loadable = { package = "sqlite-loadable", path = "./vendor/sqlite-loadable", features=["static"] }
