services:

  trail:
    build: .
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - ./traildepot:/app/traildepot
    environment:
      # Setup Rust's env-logger.
      RUST_LOG: "info,refinery_core=warn"
      RUST_BACKTRACE: "1"
    command: "/app/trail --data-dir /app/traildepot run --address 0.0.0.0:4000"
