packages:
  - 'client/trailbase-ts'
  - 'docs'
  - 'ui/admin'
  - 'ui/auth'
  - 'examples/blog/web'
  - 'examples/coffeesearch'
  - 'examples/tutorial/scripts'
  - 'trailbase-core/js'
options:
  prefer-workspace-packages: true
  strict-peer-dependencies: true
