packages:
  - 'docs'
  - 'docs/examples/record_api_ts'
  - 'examples/blog/web'
  - 'examples/coffee-vector-search'
  - 'examples/collab-clicker-ssr'
  - 'examples/data-cli-tutorial'
  - 'trailbase-core/js/admin'
  - 'trailbase-core/js/auth'
  - 'trailbase-core/js/client'
  - 'trailbase-core/js/runtime'
options:
  link-workspace-packages: true
  prefer-workspace-packages: true
  strict-peer-dependencies: true
  # shared-workspace-lockfile: false
