packages:
  - 'docs'
  - 'docs/examples/record_api_ts'
  - 'examples/blog/web'
  - 'examples/coffee-vector-search'
  - 'examples/collab-clicker-ssr'
  - 'examples/data-cli-tutorial'
  - 'trailbase-assets/js/admin'
  - 'trailbase-assets/js/auth'
  - 'trailbase-assets/js/client'
  - 'trailbase-js/assets/runtime'

sharedWorkspaceLockfile: true
linkWorkspacePackages: true
preferWorkspacePackages: true
preferOffline: true
preferFrozenLockfile: true
# strictPeerDependencies: false
disallowWorkspaceCycles: true
