packages:
  - 'docs'
  - 'trailbase-core/js/admin'
  - 'trailbase-core/js/auth'
  - 'trailbase-core/js/client'
  - 'examples/blog/web'
  - 'examples/coffeesearch'
  - 'examples/tutorial/scripts'
  - 'trailbase-core/js/runtime'
options:
  prefer-workspace-packages: true
  strict-peer-dependencies: true
