services:

  blog:
    # NOTE: We have to build relative to root to have a build context that
    # includes both: the trailbase server source and the demo wepapp sources.
    # build: ../..
    # TODO: Build from "." once the Dockerfile can pull a base image from
    # dockerhub. We still need an example Dockerfile to build the UI.
    build:
      context: ../..
      dockerfile: examples/blog/Dockerfile
    restart: unless-stopped
    environment:
      TRAIL_INITIAL_PASSWORD: secret
      ADDRESS: 0.0.0.0:4000
      PUBLIC_DIR: ./public
      DATA_DIR: ./traildepot
    volumes:
      - ./traildepot:/app/traildepot

  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
