[package]
name = "custom-binary"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "^0.8.1"
env_logger = "^0.11.3"
tokio = { version = "^1.38.0", features=["macros", "rt-multi-thread"] }
trailbase = { workspace = true }
