[package]
name = "trailbase-extension"
version = "0.1.1"
edition = "2021"
license = "OSL-3.0"
description = "SQLite extension used by TrailBase"
homepage = "https://trailbase.io"
repository = "https://github.com/trailbaseio/trailbase"
readme = "../README.md"

[lib]
crate-type=["cdylib", "rlib"]

[dependencies]
argon2 = "0.5.3"
base64 = "0.22.1"
jsonschema = { version = "0.28.0", default-features = false }
lru = { version = "0.12.3", default-features = false }
maxminddb = "0.24.0"
parking_lot = { version = "0.12.3", default-features = false }
rand = "0.8.5"
regex = "1.11.0"
rusqlite = { workspace = true }
serde_json = "1.0.121"
uuid = { version = "1.7.0", default-features = false, features = ["std", "v7"] }
validator = "0.20.0"

[dev-dependencies]
uuid = { version = "1.7.0", default-features = false, features = ["std", "v4", "v7"] }

[profile.release]
strip = "debuginfo"
opt-level = "s"
panic = "unwind"
lto = true
